### ISSUE TITLE
RecyclerView设置LayoutManager为StaggeredGridLayoutManager时，数据全部加载完了，却一直显示正在加载的状态

### ISSUE THREAD

**Issue by jamin918** [Bakumon/BkLoadMore#1]
非常感谢作者提供这个库，在使用的过程中发现了点问题：
1、recyclerView.setLayoutManager(new StaggeredGridLayoutManager(3, StaggeredGridLayoutManager.VERTICAL)); 数据全部加载完了，却一直显示加载中的状态。

2、recyclerView.setLayoutManager(new GridLayoutManager(this, 3));  加载失败的item没有占满整个屏幕的宽，只是占据GridView的item宽度。

onAdapterDataChanged() 方法中调用了displayRow()方法，接着在checkEndOffset()方法中又调用了displayRow()方法，是不是重复调用了，我注释掉了onAdapterDataChanged() 方法中的displayRow()方法，再次运行后发现效果是一样的。
       希望作者看到后能及时修复一下，谢谢。

**Comment by Bakumon** [comment]
感谢反馈，问题已经解决，是因为在 `setIsLastPage(boolean isLastPage)` 方法中没有手动设置显示“没有更多数据”行，`LinearLayoutManager` 没有这个问题。`StaggeredGridLayoutManager` 和 `GridLayoutManager` 在没有更多数据时，没有回调数据观察者。

注释掉了多余的调用。感谢提醒。

具体解决代码，请看 [commit fixed #1](https://github.com/Bakumon/BkLoadMore/commit/fbf0dafe2d66ed0595325d0a5208861affd59468)
